version: 0.2
phases:
  pre_build:
    commands:
    - echo Logging in to Docker Hub...
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - REPOSITORY_URI=docker.io/$DOCKER_USER/esctfdemo    
    - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
    - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker images...
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - docker push $REPOSITORY_URI:latest 
    - kubectl get nodes
 
 